#ifndef _FILEPATHS_H__
#define _FILEPATHS_H__

#define HOME "${ACFSUPERVISOR_ROOT}"
#define XSLSTYLESHEET "${ACFSUPERVISOR_ROOT}/xml/XMLtoHTML.xsl"
#define XMLSTYLESHEET "${ACFSUPERVISOR_ROOT}/xml/HTMLtoXML.xsl"
#define SETTINGSSTYLESHEET "${ACFSUPERVISOR_ROOT}/xml/SettingsXMLtoHTML.xsl"
#define SETTINGSSTYLESHEETINVERSE "${ACFSUPERVISOR_ROOT}/xml/SettingsHTMLtoXML.xsl"
#define CSSSTYLESHEET "${ACFSUPERVISOR_ROOT}/html/Stylesheet.css"

#endif
