#ifndef _FILEPATHS_H__
#define _FILEPATHS_H__

#define HOME "${DTCSUPERVISOR_ROOT}"
#define XSLSTYLESHEET "${DTCSUPERVISOR_ROOT}/xml/XMLtoHTML.xsl"
#define XMLSTYLESHEET "${DTCSUPERVISOR_ROOT}/xml/HTMLtoXML.xsl"
#define SETTINGSSTYLESHEET "${DTCSUPERVISOR_ROOT}/xml/SettingsXMLtoHTML.xsl"
#define SETTINGSSTYLESHEETINVERSE "${DTCSUPERVISOR_ROOT}/xml/SettingsHTMLtoXML.xsl"
#define CSSSTYLESHEET "${DTCSUPERVISOR_ROOT}/html/Stylesheet.css"

#endif
